[package]
name = "noodles_bcf_gt_reading_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noodles = { version = "0.41.0", features = ["bgzf", "bcf", "vcf"] }
